version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tg_bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassDb
    volumes:
      - ./liquibase:/liquibase
      - ./changelog_message.sql:/liquibase/frequency_of_pulling.sql
    ports:
      - 5432:5432